fsprojects/FSharp.Control.AsyncSeq

RELEASE_NOTES.md
docs/content/index.md
docs/content/library/AsyncSeq.fsx
docs/tools/templates/template.cshtml
src/FSharp.Control.AsyncSeq/AssemblyInfo.fs
src/FSharp.Control.AsyncSeq/AsyncSeq.fs

This makes the Nil/Cons in the representation internal.  This seems a good idea for future optimizations.  Ideally the whole representation of the type would be hidden but that hasn't yet been done.

Update verision, make Nil/Cons internal

---

RELEASE_NOTES.md

The "For" combinatory is a bit too eager - it immediately creates an enumerator, when it should do it once each time the resulting AsyncSeq is iterated.

For is too eager

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs
src/FSharp.Control.AsyncSeq/AsyncSeq.fsi
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

Adds AsyncSeq.sum, length, contains, exists, forall, tryPick, tryFind

Add more operations

---

RELEASE_NOTES.md
src/FSharp.Control.AsyncSeq/AssemblyInfo.fs
src/FSharp.Control.AsyncSeq/AsyncSeq.fs
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

Fixes #35 by cleaning up the code to track the exact state at each point of the iteration objects. The use of unions is nice, it should have been written like this in the first place.

Fix 35 - leak in append

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fsi

Sorry to waste your time with such a minor PR but the extra forward slash prevents "the processing of an element completes." from being included in the IntelliSense for `iterAsync`. Without this line the documentation reads
>Iterates over the input sequence and calls the specified asynchronous function for every value. The input sequence will be asked for the next element after
Which leaves you wondering when the next element is requested! :smile:

Remove extraneous forward slash in iterAsync documentation comment

---

paket.dependencies
paket.lock

I'm having trouble building the nuget package, but this gets things a bit further
It's now failing with this (at end of build):
```
Starting Target: NuGet (==> All)
C:\GitHub\dsyme\FSharp.Control.AsyncSeq\.paket\paket.exe pack output "./temp"  v
ersion  2.0.3 releaseNotes  "Fix bug in Async.cache [#33](https://github.com/fsp
rojects/FSharp.Control.AsyncSeq/issues/33)"
Paket version 2.32.5.0
No platform specified; found output path node for the AnyCPU platform after fail
ing to find one for the following:
Paket failed with:
Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=n
eutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system
cannot find the file specified.
Running build failed.
Error:
System.Exception: Error during packing ..
at …
```

fix paket refs

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs

`DateTime.Now` is unsuitable for timing of operations, as it relies on the system clock which can be adjusted by the OS for clock drift, NTP sync, or manually by the user.  Additionally, it relies on the local time zone, which might be subject to daylight saving time changes, or (again) changes by the user.
Instead, timing operations (profiling, really) should use `System.Diagnostics.Stopwatch`.
More on this [here](http://codeofmatt.com/2013/04/25/the-case-against-datetime-now/) and [here](http://codeofmatt.com/2015/03/06/common-daylight-saving-time-mistakes-for-net-developers/).
Note that I use the static `GetTimestamp` method instead of instantiating an instance of the `Stopwatch` class.  While both APIs are valid, this one is preferred when there's a potential for multiple …

Use Stopwatch instead of DateTime

---

docs/content/library/AsyncSeqExamples.fsx
src/FSharp.Control.AsyncSeq/AsyncSeq.fs
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqPerf.fsx
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs
tests/FSharp.Control.AsyncSeq.Tests/FSharp.Control.AsyncSeq.Tests.fsproj

This contains performance improvements referenced [here](https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/50) and [here](https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/52)
The improvements made were:
- a better append implementation based on the append implementation of `seq<_>`
- fused operations via AsyncSeqOp, which for instance fuse an unfold followed by a choose and a fold into a single instance of an AsyncSeq rather than creating intermediate instances
The latter approach needs to be expanded across other operations. Also, I would like to try a few variations to see if we can get better reuse.

performance improvements

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

Added tests for bufferByTime/bufferByCountAndTime (timing based tests, but should be little risk of false positives from them I think). Could probably be simpler, but this way worked out using the reported repro.
While I focused on those two for the tests since that's what the original issue reported (and bufferByCountAndTime was my use case too), I noticed chooseTasks/2 are being used in quite a few functions, so not sure if there should be more tests added.
Should fix #65

Replace use of Task.WaitAny for Task.WhenAny

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

By moving the last emitted task to the end of the array, this algorithm achieves max-min fairness when merging AsyncSeqs. Also reformatted function to be consistent with an indent level of 2.

mergeAll max/min fairness

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs

There is some logic to remove groups and keep track of the key that at the moment is not necessary.

Cleanup groupBy logic

---

tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

Unit test which test toArray test toList, which is tested in other test already.
Perhaps result of copy-paste bug.

Unit test claimed to test toArray but test toList.

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs
src/FSharp.Control.AsyncSeq/AsyncSeq.fsi
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

Mimic the `Seq.truncate` function. `AsyncSeq.take` behaves like `Seq.truncate` therefore
`AsyncSeq.truncate` should be there for discoverability. Changing `AsyncSeq.take` is a breaking change, but a note that count > lenght is ok should be included at least.

Add truncate as an alias to mimic Seq.

---

build.fsx
docs/tools/generate.fsx

Use FSharp.Core.dll shipped in fakebuild nuget package instead for reference documentation generation only #85.
I'm confident this change will not break the CI build as the generate documentation targets are not called.

get reference documentation output from build again

---

.travis.yml
build.fsx

mono build fix attempt

---

src/FSharp.Control.AsyncSeq/FSharp.Control.AsyncSeq.fsproj

Fable compilation currently fails when including this project as the `AsyncSeq.fsi` file is not specified to be copied in `<Content Include="*.fsproj; **\*.fs;" PackagePath="fable\" />`. This pull requests adds .fsi files to the Fable package path, fixing Fable compilation errors.

Include .fsi files into Fable package path

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs

I needed to make my project target netstandard2.1 to use the latest version of FSharp.Control.AsyncSeq, but it no longer compiled with Fable.
The cause is a simple misplaced `#ifdef` in FSharp.Control.AsyncSeq that I fixed in this PR.
There is already an open PR here with that fix, but it's mixed with other things. The author, @alfonsogarciacaro, has been informed (see https://github.com/fable-compiler/Fable/issues/2299#issuecomment-735118635)

Fix compiling with Fable when targeting netstandard2.1 or netcoreapp3.0

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

Fixes this issue: https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/122

Fixed issue with iterAsyncParallel/iterAsyncParallelThrottled/mapAsyncParallel not respecting cancellation requests

---

src/FSharp.Control.AsyncSeq/AsyncSeq.fs
src/FSharp.Control.AsyncSeq/AsyncSeq.fsi
tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs

This PR implements `sort`, `sortBy`, `sortDescending` and `sortByDescending` functions and addresses the issue/feature request #126 
I have assumed that `AsyncSeq` is more about asynchronous nature of the type than the infinite nature of it. Therefore, I have implemented these using `Seq.sort`, `Seq.sortBy`, `Seq.sortDescending` and `Seq.sortByDescending` i.e. I have not considered implementing some sort of time-windowed sorting feature. Like their `Seq` counterparts, these functions are not intended to be used in large or infinite sequences.
In terms of unit testing, I have added just a test each for testing integer sequences. This feels like a good usecase for property-based testing using a framework like `FsCheck` but I haven't seen any property-based tests here so decided not to …

Sort functions

---

src/FSharp.Control.AsyncSeq/FSharp.Control.AsyncSeq.fsproj

Related to #168
Update the Nuget package license link to fix the 404 error.
* Change the `PackageLicenseUrl` in `src/FSharp.Control.AsyncSeq/FSharp.Control.AsyncSeq.fsproj` to `https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/main/LICENSE.md`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/fsprojects/FSharp.Control.AsyncSeq/issues/168?shareId=b884215d-24fb-4ad2-8c58-ccb5c151a045).

Fix Nuget package license link
